# Generated by Django 5.0.6 on 2024-06-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textcrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
